#!/usr/bin/python3

def raise_exception():
    raise Exception("This is an exception")
    raise TypeError("Error Occured")
    raise ValueError("Error Occured")
    raise NameError("Error Occured")
    raise SyntaxError("Error Occured")
    raise IndentationError("Error Occured")
    raise IndexError("Error Occured")
    raise KeyError("Error Occured")
    raise AttributeError("Error Occured")
    raise MemoryError("Error Occured")
    raise RuntimeError("Error Occured")
    raise SystemError("Error Occured")
    raise FileNotFoundError("Error Occured")
    raise IOError("Error Occured")
    raise EOFError("Error Occured")
    raise ImportError("Error Occured")
    raise ModuleNotFoundError("Error Occured")
    raise AttributeError("Error Occured")
    raise BufferError("Error Occured")
